### ISSUE TITLE
Add crossorigin attribute to preconnect links

### ISSUE THREAD

**Issue by seaneking** [NoriSte/gatsby-plugin-preconnect#334]
Without specifying a `crossorigin` attribute on preconnect links, browsers will only do a DNS prefetch rather than actually connecting to the resource.

```html
<link href="..." rel="preconnect" crossorigin>
```

**Comment by NoriSte** [comment]
Hi @seaneking 
Thank you! As far as I know:
- `crossorigin` (that means `crossorigin=anonymous""`) must be explicit if you are going to load some CORS resources (like XHRs)

**Comment by seaneking** [comment]
Hmm yeah It's a really poorly documented standard, I don't _think_ there's any harm in including `crossorigin` for all preconnect (as opposed to prefetch) requests, because you're not 'preconnecting' to a specific resource but to a domain, and if crossorigin isn't required it should just be ignored.

But I'm not 100% on that. Maybe to be safe the plugin could take either an array of strings (basic preconnect), or objects (preconnect href + options like crossorigin), so users could set per domain if they wanted?

Something like:

```
{ 
  resolve: 'gatsby-plugin-preconnect',
  options: {
    domains: [
       'https://foo.com', // Default preconnect
       {
          href: 'fonts.gstatic.com',  // With opts, mapped to attributes
          crossorigin: true
       }
    ]
  }
}
```

**Comment by NoriSte** [comment]
My proposal:

**Base options**
- `crossorigin` is set to `true` by default

**Advanced options**
- `domains` is:
```ts
domains:
  | string[]
  | {
    domain: string,
    crossorigin?: boolean | 'use-credentials' 
  }[]
```

What do you think?

**Comment by schnogz** [comment]
I agree that `crossorigin` should be enabled by default. Your proposal for advanced options looks fine as well.

**Comment by seaneking** [comment]
Yep agree, looks great 👍

**Comment by NoriSte** [comment]
Thanks, I'll review the PR it in the next few days 😊

**Comment by NoriSte** [comment]
I probably should re-check the various options and the result but, meantime, I  share it with you 😉

**Comment by NoriSte** [comment]
@seaneking , @schnogz thanks for everything, I've added you in the contributors list 😊 as soon as the test spass I'll release it 😊

**Comment by NoriSte** [comment]
`v1.1.0` has been published 🚀 thanks guys!!!!

**Comment by Floriferous** [comment]
Thanks for this feature! I came here due to lighthouse recommending it.

After setting it up, I still get some warnings, and I'm not sure what the right setting should be.

```
A preconnect <link> was found for "https://www.googletagmanager.com" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
```

I simply kept crossorigin to undefined. 

I know it's not really the job of this plugin, but it'd be helpful if it were briefly documented how to use it in most cases :)
