### ISSUE TITLE
Provide compatibility with Gatsby v5

### ISSUE THREAD

**Issue by nikolay543** [NoriSte/gatsby-plugin-preconnect#642]
Can you please update the peerDependencies to include gatsby v5?

```
"peerDependencies": {
    "gatsby": "^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0"
 }
```

**Comment by NoriSte** [comment]
I checked the migration guide and updating the peer dependent should be enough. I'll regenerate the projects I use to test the plugin and if the automatic tests pass I can release it. No precise ETA, it should be next week BTW.

Thank you
Best
Stefano

**Comment by nikolay543** [comment]
Thank you @NoriSte, you are a lifesaver

**Comment by NoriSte** [comment]
Just released v1.4.0, can you confirm it works, please? 😊

**Comment by nikolay543** [comment]
Works like a charm 🙇

**Comment by NoriSte** [comment]
Cool! Thanks for the feedback 😊
